version: '3.9'

services:
  db.vitl:
    restart: unless-stopped
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: vitl
      MYSQL_USER: vitl
      MYSQL_PASSWORD: password
    volumes:
      - ./mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - db.vitl:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db.vitl:
    external: true